name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: break-continue-test
      id: break-continue-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: break-continue-test
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BREAK-CONTINUE-TEST_RESULTS: "${{steps.break-continue-test.outputs.result}}"
      with:
        runners: break-continue-test
